name: 'Arduino Continuous Deployment'
description: 'OTA Update via MQTT and HTTP for Arduino'
inputs:
  deviceId:
    description: 'To be deployed device id'
    required: true
    default: ''
  binaryBuildPath:
    description: 'Path to binary build folder'
    required: true
    default: ''
  mqttUrl:
    description: 'MQTT URL'
    required: true
    default: ''
  mqttUsername:
    description: 'MQTT username'
    required: true
    default: ''
  mqttPassword:
    description: 'MQTT password'
    required: true
    default: ''
  mqttTopic:
    description: 'MQTT update topic'
    required: false
    default: 'main/update'
  timeLimit:
    description: 'Deployment time limit in ms'
    required: false
    default: 120000
outputs:
  result:
    description: 'Deployment result'
runs:
  using: 'node16'
  main: 'dist/index.js'
